/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_products__product_id__get"];
        /** Update Product */
        put: operations["update_product_api_products__product_id__put"];
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_products__product_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stock */
        get: operations["list_stock_api_stock_get"];
        put?: never;
        /** Add Stock */
        post: operations["add_stock_api_stock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Available */
        get: operations["get_available_api_stock_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/expiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Expiring */
        get: operations["get_expiring_api_stock_expiring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock Entry */
        get: operations["get_stock_entry_api_stock__entry_id__get"];
        /** Update Stock */
        put: operations["update_stock_api_stock__entry_id__put"];
        post?: never;
        /** Delete Stock */
        delete: operations["delete_stock_api_stock__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume */
        post: operations["consume_api_stock_consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/consume-recipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume Recipe */
        post: operations["consume_recipe_api_stock_consume_recipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/barcode/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Barcode */
        get: operations["lookup_barcode_api_barcode__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/consumption": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consumption Stats */
        get: operations["consumption_stats_api_stats_consumption_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/waste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Waste Stats */
        get: operations["waste_stats_api_stats_waste_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/expiry-forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expiry Forecast */
        get: operations["expiry_forecast_api_stats_expiry_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Category Analytics */
        get: operations["category_analytics_api_stats_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Low Stock */
        get: operations["low_stock_api_stats_low_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/turnover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Turnover Rates
         * @description Verbrauchsraten in einem Abruf statt einem je Produkt.
         *
         *     ★ Gegenstueck zu ``/turnover/{product_id}``, angelegt am 2026-09-13, weil
         *     mealprep die Einzelauskunft in einer Schleife rief: 14 Anfragen fuer ein
         *     Dashboard bei einem Deckel von 60 je Minute. Wer hier fragt, bezahlt eine.
         *
         *     Produkte ohne Verbrauch im Zeitraum fehlen in der Antwort. Das ist der
         *     Unterschied zwischen "gemessen, keine Bewegung" und "nicht gemessen": eine
         *     Antwort mit weniger Zeilen ist eine Messung, ein Fehlschlag ist ein
         *     Fehlerstatus. Wer beides gleich behandelt, baut sich Nullen, die wie Daten
         *     aussehen.
         */
        get: operations["turnover_rates_api_stats_turnover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/turnover/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Turnover Rate */
        get: operations["turnover_rate_api_stats_turnover__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/critical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Critical Stock */
        get: operations["critical_stock_api_critical_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/electronics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_electronics_get"];
        put?: never;
        /** Create Asset */
        post: operations["create_asset_api_electronics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/electronics/sell-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sell Candidates */
        get: operations["sell_candidates_api_electronics_sell_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/electronics/homelab/seed-known": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Homelab Assets */
        post: operations["seed_homelab_assets_api_electronics_homelab_seed_known_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/electronics/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio
         * @description Wertsachen-Portfolio: Kennzahlen + Kategorien + Verkaufsempfehlungen.
         *
         *     Ersetzt die saganta assets-App (Super-App-Merge Phase 3). Marktwert =
         *     effective_market_value (marktwatch-Median, Fallback manueller Schätzwert).
         */
        get: operations["portfolio_api_electronics_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/electronics/{asset_id}/refresh-market-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Asset Market Value */
        post: operations["refresh_asset_market_value_api_electronics__asset_id__refresh_market_value_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/electronics/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_electronics__asset_id__get"];
        /** Update Asset */
        put: operations["update_asset_api_electronics__asset_id__put"];
        post?: never;
        /** Delete Asset */
        delete: operations["delete_asset_api_electronics__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shopping List */
        get: operations["shopping_list_api_shopping_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recipes */
        get: operations["list_recipes_api_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Meal Plan */
        post: operations["meal_plan_api_meal_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Health */
        get: operations["api_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvailabilityOut */
        AvailabilityOut: {
            /** Product Id */
            product_id: number;
            /** Unit */
            unit: string;
            /** Total */
            total: number;
        };
        /** CategoryAnalyticsItem */
        CategoryAnalyticsItem: {
            /** Category */
            category: string;
            /** Total Items */
            total_items: number;
            /** Total Consumed */
            total_consumed: number;
            /** Total Expired */
            total_expired: number;
            /** Waste Percent */
            waste_percent: number;
        };
        /** ConsumeRecipeRequest */
        ConsumeRecipeRequest: {
            /** Ingredients */
            ingredients: components["schemas"]["ConsumeRequest"][];
        };
        /** ConsumeRequest */
        ConsumeRequest: {
            /** Product Id */
            product_id: number;
            /** Amount */
            amount: number;
            /**
             * Unit
             * @default g
             */
            unit?: string;
            /**
             * Reason
             * @default verbraucht
             */
            reason?: string;
            /**
             * Source
             * @default manual
             */
            source?: string;
            /** Ref Type */
            ref_type?: string | null;
            /** Ref Id */
            ref_id?: number | null;
        };
        /** ConsumptionByProduct */
        ConsumptionByProduct: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Total Amount */
            total_amount: number;
            /** Unit */
            unit: string;
            /** Event Count */
            event_count: number;
        };
        /** ConsumptionEventOut */
        ConsumptionEventOut: {
            /** Id */
            id: number;
            /** Stock Entry Id */
            stock_entry_id: number;
            /** Amount */
            amount: number;
            /** Unit */
            unit: string;
            /**
             * Consumed At
             * Format: date-time
             */
            consumed_at: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
        };
        /** ElectronicAssetCreate */
        ElectronicAssetCreate: {
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /** Brand */
            brand?: string | null;
            /** Model */
            model?: string | null;
            /** Serial */
            serial?: string | null;
            /** Barcode */
            barcode?: string | null;
            /**
             * Condition
             * @default gut
             */
            condition?: string;
            /**
             * Status
             * @default aktiv
             */
            status?: string;
            /**
             * Location
             * @default Elektronik
             */
            location?: string;
            /**
             * Usage Status
             * @default reserve
             */
            usage_status?: string;
            /** Homelab Role */
            homelab_role?: string | null;
            /** Host Name */
            host_name?: string | null;
            /**
             * Service Refs
             * @default []
             */
            service_refs?: string[];
            /** Purchase Date */
            purchase_date?: string | null;
            /** Purchase Price */
            purchase_price?: number | null;
            /** Purchase Source */
            purchase_source?: string | null;
            /** Purchase Url */
            purchase_url?: string | null;
            /** Warranty End */
            warranty_end?: string | null;
            /** Estimated Resale Value */
            estimated_resale_value?: number | null;
            /** Resale Confidence */
            resale_confidence?: string | null;
            /**
             * Sell Decision
             * @default behalten
             */
            sell_decision?: string;
            /** Sell Reason */
            sell_reason?: string | null;
            /** Desired Min Profit */
            desired_min_profit?: number | null;
            /**
             * Manual Pin
             * @default false
             */
            manual_pin?: boolean;
            /** Ebay Item Id */
            ebay_item_id?: string | null;
            /** Ebay Watch Query */
            ebay_watch_query?: string | null;
            /**
             * External Refs
             * @default {}
             */
            external_refs?: {
                [key: string]: unknown;
            };
            /** Notes */
            notes?: string | null;
        };
        /** ElectronicAssetOut */
        ElectronicAssetOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Brand */
            brand: string | null;
            /** Model */
            model: string | null;
            /** Serial */
            serial: string | null;
            /** Barcode */
            barcode: string | null;
            /** Condition */
            condition: string;
            /** Status */
            status: string;
            /** Location */
            location: string;
            /** Usage Status */
            usage_status: string;
            /** Homelab Role */
            homelab_role: string | null;
            /** Host Name */
            host_name: string | null;
            /** Service Refs */
            service_refs: string[];
            /** In Active Use */
            in_active_use: boolean;
            /** Purchase Date */
            purchase_date: string | null;
            /** Purchase Price */
            purchase_price: number | null;
            /** Purchase Source */
            purchase_source: string | null;
            /** Purchase Url */
            purchase_url: string | null;
            /** Warranty End */
            warranty_end: string | null;
            /** Estimated Resale Value */
            estimated_resale_value: number | null;
            /** Market Value Eur */
            market_value_eur?: number | null;
            /** Market Value At */
            market_value_at?: string | null;
            /** Effective Market Value */
            effective_market_value?: number | null;
            /** Resale Confidence */
            resale_confidence: string | null;
            /** Sell Decision */
            sell_decision: string;
            /** Sell Reason */
            sell_reason: string | null;
            /** Desired Min Profit */
            desired_min_profit: number | null;
            /** Manual Pin */
            manual_pin: boolean;
            /** Estimated Profit */
            estimated_profit?: number | null;
            /** Ebay Item Id */
            ebay_item_id: string | null;
            /** Ebay Watch Query */
            ebay_watch_query: string | null;
            /**
             * External Refs
             * @default {}
             */
            external_refs?: {
                [key: string]: unknown;
            };
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ElectronicAssetUpdate */
        ElectronicAssetUpdate: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Brand */
            brand?: string | null;
            /** Model */
            model?: string | null;
            /** Serial */
            serial?: string | null;
            /** Barcode */
            barcode?: string | null;
            /** Condition */
            condition?: string | null;
            /** Status */
            status?: string | null;
            /** Location */
            location?: string | null;
            /** Usage Status */
            usage_status?: string | null;
            /** Homelab Role */
            homelab_role?: string | null;
            /** Host Name */
            host_name?: string | null;
            /** Service Refs */
            service_refs?: string[] | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Purchase Price */
            purchase_price?: number | null;
            /** Purchase Source */
            purchase_source?: string | null;
            /** Purchase Url */
            purchase_url?: string | null;
            /** Warranty End */
            warranty_end?: string | null;
            /** Estimated Resale Value */
            estimated_resale_value?: number | null;
            /** Resale Confidence */
            resale_confidence?: string | null;
            /** Sell Decision */
            sell_decision?: string | null;
            /** Sell Reason */
            sell_reason?: string | null;
            /** Desired Min Profit */
            desired_min_profit?: number | null;
            /** Manual Pin */
            manual_pin?: boolean | null;
            /** Ebay Item Id */
            ebay_item_id?: string | null;
            /** Ebay Watch Query */
            ebay_watch_query?: string | null;
            /** External Refs */
            external_refs?: {
                [key: string]: unknown;
            } | null;
            /** Notes */
            notes?: string | null;
        };
        /** ExpiryForecastItem */
        ExpiryForecastItem: {
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
            /** Mhd */
            mhd: string | null;
            /** Days Left */
            days_left: number | null;
            /** Urgency */
            urgency: string;
            /** Location */
            location: string;
        };
        /** ForecastItemOut */
        ForecastItemOut: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Days Left */
            days_left: number;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LowStockItem */
        LowStockItem: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Current Stock */
            current_stock: number;
            /** Min Stock */
            min_stock: number;
            /** Min Stock Unit */
            min_stock_unit: string;
            /** Deficit */
            deficit: number;
        };
        /** MarketValueUpdateOut */
        MarketValueUpdateOut: {
            /** Asset Id */
            asset_id: number;
            /** Market Value Eur */
            market_value_eur: number | null;
            /** Market Value At */
            market_value_at: string | null;
            /** Samples */
            samples: number;
            /** From Cache */
            from_cache: boolean;
        };
        /** MealPlanMissingProduct */
        MealPlanMissingProduct: {
            /** Product Id */
            product_id: number | null;
            /** Product Name */
            product_name: string;
            /** Needed */
            needed: number;
            /** Unit */
            unit: string;
        };
        /** MealPlanRecipe */
        MealPlanRecipe: {
            /** Recipe Id */
            recipe_id: string;
            /** Name */
            name: string;
            /** Servings */
            servings: number;
        };
        /** MealPlanRequest */
        MealPlanRequest: {
            /** Recipe Ids */
            recipe_ids: string[];
            /**
             * Servings
             * @default 2
             */
            servings?: number;
        };
        /** MealPlanResponse */
        MealPlanResponse: {
            /** Requested */
            requested: components["schemas"]["MealPlanRecipe"][];
            /** Shopping List */
            shopping_list: components["schemas"]["MealPlanShoppingItem"][];
            /** Missing Stock */
            missing_stock: components["schemas"]["MealPlanMissingProduct"][];
        };
        /** MealPlanShoppingItem */
        MealPlanShoppingItem: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Needed */
            needed: number;
            /** Available */
            available: number;
            /** Missing */
            missing: number;
            /** Unit */
            unit: string;
        };
        /** NutritionInfo */
        NutritionInfo: {
            /**
             * Kcal
             * @default 0
             */
            kcal?: number;
            /**
             * Protein G
             * @default 0
             */
            protein_g?: number;
            /**
             * Carbs G
             * @default 0
             */
            carbs_g?: number;
            /**
             * Fat G
             * @default 0
             */
            fat_g?: number;
            /**
             * Fiber G
             * @default 0
             */
            fiber_g?: number;
        };
        /** Page[ElectronicAssetOut] */
        Page_ElectronicAssetOut_: {
            /** Items */
            items: components["schemas"]["ElectronicAssetOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[ProductOut] */
        Page_ProductOut_: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[StockEntryOut] */
        Page_StockEntryOut_: {
            /** Items */
            items: components["schemas"]["StockEntryOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** PortfolioCategoryOut */
        PortfolioCategoryOut: {
            /** Category */
            category: string;
            /** Count */
            count: number;
            /** Market Value */
            market_value: number;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Total Assets */
            total_assets: number;
            /** Market Value Total */
            market_value_total: number;
            /** Valued Count */
            valued_count: number;
            /** Purchase Total */
            purchase_total: number;
            /** Delta Vs Purchase */
            delta_vs_purchase: number;
            /** Delta Count */
            delta_count: number;
            /** Categories */
            categories: components["schemas"]["PortfolioCategoryOut"][];
            /** Resale Recommendations */
            resale_recommendations: components["schemas"]["PortfolioResaleOut"][];
        };
        /** PortfolioResaleOut */
        PortfolioResaleOut: {
            /** Asset Id */
            asset_id: number;
            /** Name */
            name: string;
            /** Market Value Eur */
            market_value_eur: number | null;
            /** Reason */
            reason: string;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Barcode */
            barcode?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Default Unit
             * @default g
             */
            default_unit?: string;
            nutrition_per_100?: components["schemas"]["NutritionInfo"] | null;
            /**
             * Typical Pack Sizes
             * @default []
             */
            typical_pack_sizes?: number[];
            /**
             * Shelf Life Type
             * @default MHD
             */
            shelf_life_type?: string;
            /** Shelf Life Days Default */
            shelf_life_days_default?: number | null;
            /** Image Url */
            image_url?: string | null;
            /**
             * Synonyms
             * @default []
             */
            synonyms?: string[];
            /** Min Stock */
            min_stock?: number | null;
            /** Min Stock Unit */
            min_stock_unit?: string | null;
        };
        /** ProductOut */
        ProductOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Barcode */
            barcode: string | null;
            /** Category */
            category: string | null;
            /** Default Unit */
            default_unit: string;
            nutrition_per_100: components["schemas"]["NutritionInfo"] | null;
            /** Typical Pack Sizes */
            typical_pack_sizes: number[];
            /** Shelf Life Type */
            shelf_life_type: string;
            /** Shelf Life Days Default */
            shelf_life_days_default: number | null;
            /** Image Url */
            image_url: string | null;
            /**
             * Synonyms
             * @default []
             */
            synonyms?: string[];
            /** Min Stock */
            min_stock?: number | null;
            /** Min Stock Unit */
            min_stock_unit?: string | null;
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Barcode */
            barcode?: string | null;
            /** Category */
            category?: string | null;
            /** Default Unit */
            default_unit?: string | null;
            nutrition_per_100?: components["schemas"]["NutritionInfo"] | null;
            /** Typical Pack Sizes */
            typical_pack_sizes?: number[] | null;
            /** Shelf Life Type */
            shelf_life_type?: string | null;
            /** Shelf Life Days Default */
            shelf_life_days_default?: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Synonyms */
            synonyms?: string[] | null;
            /** Min Stock */
            min_stock?: number | null;
            /** Min Stock Unit */
            min_stock_unit?: string | null;
        };
        /** RecipeOut */
        RecipeOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Servings Default */
            servings_default: number;
            /** Ingredients */
            ingredients: {
                [key: string]: unknown;
            }[];
        };
        /** SellRecommendationOut */
        SellRecommendationOut: {
            /** Asset Id */
            asset_id: number;
            /** Name */
            name: string;
            /** Decision */
            decision: string;
            /** Reason */
            reason: string;
            /** Purchase Price */
            purchase_price: number | null;
            /** Estimated Resale Value */
            estimated_resale_value: number | null;
            /** Estimated Profit */
            estimated_profit: number | null;
            /** Warranty Days Left */
            warranty_days_left?: number | null;
            /** Ebay Watch Query */
            ebay_watch_query?: string | null;
            /** Usage Status */
            usage_status?: string | null;
            /** Homelab Role */
            homelab_role?: string | null;
            /** Host Name */
            host_name?: string | null;
        };
        /** ShoppingSuggestionOut */
        ShoppingSuggestionOut: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Suggested Quantity */
            suggested_quantity: number;
            /** Unit */
            unit: string;
            /** Reason */
            reason: string;
            /** Current Stock */
            current_stock: number;
        };
        /** StockEntryCreate */
        StockEntryCreate: {
            /** Product Id */
            product_id: number;
            /** Quantity */
            quantity: number;
            /**
             * Unit
             * @default g
             */
            unit?: string;
            /** Mhd */
            mhd?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /**
             * Location
             * @default Vorratskammer
             */
            location?: string;
            /** Lot Note */
            lot_note?: string | null;
        };
        /** StockEntryOut */
        StockEntryOut: {
            /** Id */
            id: number;
            /** Product Id */
            product_id: number;
            /**
             * Product Name
             * @default
             */
            product_name?: string;
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
            /** Mhd */
            mhd: string | null;
            /** Purchase Date */
            purchase_date: string | null;
            /** Location */
            location: string;
            /** Days Until Expiry */
            days_until_expiry?: number | null;
            /** Opened At */
            opened_at?: string | null;
        };
        /** StockEntryUpdate */
        StockEntryUpdate: {
            /** Quantity */
            quantity?: number | null;
            /** Unit */
            unit?: string | null;
            /** Mhd */
            mhd?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Location */
            location?: string | null;
            /** Lot Note */
            lot_note?: string | null;
            /** Opened At */
            opened_at?: string | null;
        };
        /** TurnoverResult */
        TurnoverResult: {
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Avg Daily */
            avg_daily: number;
            /** Unit */
            unit: string;
            /** Days Analysed */
            days_analysed: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WasteSummary */
        WasteSummary: {
            /** Total Events */
            total_events: number;
            /** Total Amount */
            total_amount: number;
            /** By Product */
            by_product: components["schemas"]["ConsumptionByProduct"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_products_api_products_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_products__product_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stock_api_stock_get: {
        parameters: {
            query?: {
                product_id?: number | null;
                location?: string | null;
                only_positive?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StockEntryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_stock_api_stock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_available_api_stock_available_get: {
        parameters: {
            query: {
                product_id: number;
                unit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expiring_api_stock_expiring_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_entry_api_stock__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stock_api_stock__entry_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stock_api_stock__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consume_api_stock_consume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumptionEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consume_recipe_api_stock_consume_recipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumeRecipeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumptionEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_barcode_api_barcode__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consumption_stats_api_stats_consumption_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumptionByProduct"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    waste_stats_api_stats_waste_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WasteSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expiry_forecast_api_stats_expiry_forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpiryForecastItem"][];
                };
            };
        };
    };
    category_analytics_api_stats_categories_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAnalyticsItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    low_stock_api_stats_low_stock_get: {
        parameters: {
            query?: {
                threshold_pct?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LowStockItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turnover_rates_api_stats_turnover_get: {
        parameters: {
            query?: {
                /** @description Kommaliste von Produkt-Nummern. Weggelassen = alle Produkte mit Verbrauch im Zeitraum. */
                product_ids?: string | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoverResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turnover_rate_api_stats_turnover__product_id__get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoverResult"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    critical_stock_api_critical_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_assets_api_electronics_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
                category?: string | null;
                sell_decision?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ElectronicAssetOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_asset_api_electronics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElectronicAssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectronicAssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sell_candidates_api_electronics_sell_candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellRecommendationOut"][];
                };
            };
        };
    };
    seed_homelab_assets_api_electronics_homelab_seed_known_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectronicAssetOut"][];
                };
            };
        };
    };
    portfolio_api_electronics_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
        };
    };
    refresh_asset_market_value_api_electronics__asset_id__refresh_market_value_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketValueUpdateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_electronics__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectronicAssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_asset_api_electronics__asset_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElectronicAssetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectronicAssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_electronics__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shopping_list_api_shopping_list_get: {
        parameters: {
            query?: {
                analysis_days?: number;
                expiring_within_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingSuggestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_api_forecast_get: {
        parameters: {
            query?: {
                days?: number;
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipes_api_recipes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOut"][];
                };
            };
        };
    };
    meal_plan_api_meal_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
